environment:
  modkey: mod4
  terminal: alacritty
  browser: firefox
  wallpaper_dir: /usr/share/backgrounds/archlinux/
  wallpaper_timeout: 30
  os_logo: /home/qtileuser/logos/linux.svg
  theme: ebenezer
  os_logo_icon: 
  os_logo_icon_color: "fg_white"
  weather_api_key: foo
  city_id: 1
  github_notifications_token: foo

groups:
  browsers: 
  terminal:  
  editors: 󰘐
  games:   
  files: 󰉋
  win: 󰍲    

groups_layout:
  default: monadtall
  win: tile
  files: floating
  editors: monadtall
  games: max

layouts:
  bsp: {}
  columns: {}
  floating: {}
  matrix: {}
  max: {}
  monadtall: {}
  monadwide: {}
  radiotile: {}
  tile:
    ratio: 0.335
    margin: 0
  treetab: {}
  verticaltile: {}
  zoomy: {}

startup:
  keyboard_layout: setxkbmap -model abnt2 -layout br && localectl set-x11-keymap br
  polkit: /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
  picom: picom --config $home/.config/picom/picom.conf --daemon 
  xrandr: xrandr --output eDP-1 --primary && xrandr --output HDMI-1 --mode 1920x1080 --left-of eDP-1 --auto
  nm_applet: nm-applet &
  lock_screen: xautolock -time 10 -locker "ebenezer ui lock" &
  wallpaper_slideshow: ebenezer wallpaper random $wallpaper_dir --timeout $wallpaper_timeout
  dunst: dunst &
  pcmanfm: pcmanfm-qt --daemon-mode &

commands:
  screenshot: flameshot gui --clipboard --path $home/Pictures/Screenshots
  screenshot_full: flameshot full --clipboard --path $home/Pictures/Screenshots
  change_wallpaper: ebenezer wallpaper set /usr/share/backgrounds/archlinux/
  mixer: pavucontrol # another option: kitty "pulsemixer"
  powermenu: ebenezer ui powermenu
  wallpaper_menu: ebenezer ui wallpaper-menu
  open_url: zen-browser --new-tab $url
  launcher: rofi -show drun -show-icons -theme $rofi_home/launcher.rasi
  launcher_windows: rofi -show window -show-icons -theme $rofi_home/launcher.rasi
  desktop_settings: ebenezer ui settings

floating:
  wm_class:
    - pavucontrol
    - Arandr
    - Blueman-manager
    - Gpick
    - Kruler
    - Sxiv
    - Tor Browser
    - Wpa_gui
    - veromix
    - xtightvncviewer
    - gnome-calculator
    - obs
  title: []

fonts:
  font: Fira Code Nerd Font Bold
  font_regular: Fira Code Nerd Font Medium
  font_light: Fira Code Nerd Font Light
  font_strong: Fira Code Nerd Font Semibold
  font_strong_bold: Fira Code Nerd Font Bold
  font_size: 14
  font_icon: Fira Code Nerd Font Medium
  font_icon_size: 16
  font_arrow: Fira Code Nerd Font Medium
  font_arrow_size: 30

keybindings:
  - { name: Launch terminal, keys: $mod Return, action: terminal }
  - { name: Launcher, keys: $mod shift Return, action: spawn_command, command: launcher }
  - { name: Launch Window, keys: $mod control Tab, action: spawn_command, command: launcher_windows }
  - { name: Web browser, keys: $mod b, action: browser }
  - { name: Lock Screen, keys: $mod control x, action: lock_screen }

  # qtile keys
  - { name: Reload the config, keys: $mod shift r, action: reload_config }
  - { name: Shutdown Qtile, keys: $mod control q, action: shutdown }

  # window key
  - { name: Toggle between layouts, keys: $mod Tab, action: next_layout }
  - { name: Kill focused window, keys: $mod shift c, action: kill_window }
  - { name: Move focus to left, keys: $mod h, action: focus_left }
  - { name: Move focus to right, keys: $mod l, action: focus_right }
  - { name: Move focus down, keys: $mod j, action: focus_down }
  - { name: Move focus up, keys: $mod k, action: focus_up }
  - { name: Move window focus to other window, keys: $mod space, action: focus_next }
  - { name: Toggle fullscreen on the focused window, keys: $mod f, action: fullscreen }
  - { name: Toggle floating on the focused window, keys: $mod t, action: floating }
  - { name: Move window to the left, keys: $mod shift h, action: shuffle_left }
  - { name: Move window to the right, keys: $mod shift l, action: shuffle_right }
  - { name: Move window down, keys: $mod shift j, action: shuffle_down }
  - { name: Move window up, keys: $mod shift k, action: shuffle_up }
  - { name: Grow window to the left, keys: $mod control h, action: grow_left }
  - { name: Grow window to the right, keys: $mod control l, action: grow_right }
  - { name: Grow window down, keys: $mod control j, action: grow_down }
  - { name: Grow window up, keys: $mod control k, action: grow_up }
  - { name: Reset all window sizes, keys: $mod n, action: reset_windows }

  # screenshot
  - { name: Take a screenshot, keys: print, action: spawn_command, command: screenshot }
  - { name: Take a screenshot of the full desktop, keys: $mod print, action: spawn_command, command: screenshot_full }

  # desktop
  - {name: Change wallpaper, keys: $mod control w, action: spawn_command, command: change_wallpaper}
  - {name: Desktop Settings, keys: $mod control Escape, action: spawn_command, command: desktop_settings}

  # options
  # - { name: Spawn a command using a prompt widget, keys: $mod r, action: cmd }

lock_screen:
  command: "~/.config/qtile/lock.py"
  timeout: 10
  font_size: 45
  font: Inter ExtraBold
  quote_font_size: 22
  quote_font_path: /usr/share/fonts/inter/IosevkaNerdFontMono-ExtraBoldOblique.ttf
  quote_font_path_alt: /usr/share/fonts/liberation/LiberationMono-Bold.ttf
  joke_providers: reddit,icanhazdad
  icanhazdad_joke_url: https://icanhazdadjoke.com/
  reddit_joke_url: https://www.reddit.com/r/ProgrammerDadJokes.json
  blurtype: "0x8"

monitoring:
  default_color: 'fg_normal'
  high_color: 'fg_orange'
  medium_color: 'fg_yellow'
  threshold_medium: 70
  threshold_high: 90
  burn: yes

bar:
  position: 'top'
  size: 34
  widgets:
    - type: 'group_box'
      margin_y: 3
      margin_x: 3
      padding: 0
      borderwidth: 0
      active: fg_normal
      inactive: fg_normal
      this_current_screen_border: bg_topbar_selected
      this_screen_border: fg_blue
      other_current_screen_border: bg_topbar_selected
      highlight_color: bg_topbar_selected
      highlight_method: text
      foreground: fg_normal
      rounded: false
      urgent_alert_method: border
      urgent_border: fg_urgent
    - type: 'separator'
    - type: 'task_list'
    #- type: 'weather'
    - type: 'spacer'
      length: 5
    - type: 'clock'
    - type: 'spacer'
      length: 5
    - type: 'notification'
      animated: true
    - type: 'spacer'
      length: 'stretch'
    - type: 'arrow'
    #- type: 'github'
    #- type: 'thermal'
    #  sensor:
    #    threshold_medium: 55
    #    threshold_high: 65
    - type: 'cpu'
      sensor:
        threshold_medium: 65
        threshold_high: 85
    - type: 'memory'
      sensor:
        threshold_medium: 65
        threshold_high: 85
    - type: 'battery'
    - type: 'volume'
    - type: 'powermenu'
    - type: 'hidden_tray'
    - type: 'current_layout'
